---

- name: Gather Nexus Facts
  hosts: switches
  connection: httpapi
  gather_facts: yes

  tasks:
    - nxos_facts:
    - name: Get Model
      debug: var=ansible_net_model
    - name: Get Version
      debug: var=ansible_net_version
